// Fizemos um objeto API para alimentar nossa aplicação
export const data = [
    {
      id: 0,
      nameservice: 'Pézin do Jaca',
      nameprofile: 'Perigo Original',
      profilePhoto: require('./assets/profilephoto.png'),
      backgroundPhoto: require('./assets/banner.png'),
      services: '20k',
      serviceAvaliation: 4.9,
      serviceLikes: 4.9,
      price: '42,00',
      description: 'É um corte lindo e muito bom, mas o melhor de tudo é que esse é o ORIGINAL.',
      isFavourite: false,
    },
    {
        id: 1,
        nameservice: "Tesourada da Vanessa",
        nameprofile: 'A Vanessa',
        profilePhoto: require('./assets/profilePhoto3.png'),
        backgroundPhoto: require('./assets/banner2.png'),
        services: '7.5k',
        serviceAvaliation: 4.2,
        serviceLikes: 3.7,
        price: '32,90',
        description: 'O seu lugar para sair LINDA e PODEROSA!',
        isFavourite: true,
    },
    {
        id: 2,
        nameservice: "Corte do Lulao",
        nameprofile: 'Inácio',
        profilePhoto: require('./assets/profilePhoto4.png'),
        backgroundPhoto: require('./assets/banner3.png'),
        services: '105M',
        serviceAvaliation: 3.5,
        serviceLikes: 3.5,
        price: '13,00',
        description: 'O serviço que vai roubar seu coração!',
        isFavourite: false,
    },
    {
        id: 3,
        nameservice: "Penteado Johnny Bravo",
        nameprofile: 'Johnny Bravo',
        profilePhoto: require('./assets/profilePhoto5.png'),
        backgroundPhoto: require('./assets/serviceCard2.png'),
        services: '25M',
        serviceAvaliation: 4.5,
        serviceLikes: 4.1,
        price: '100,00',
        description: 'Gata, não sou o Jota Quest, mas to fácil, EXTREMAMENTE FÁCIL!',
        isFavourite: true,
    },

]